# This workflow will build usbmuxd

name: usbmuxd CI (no tests)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: update package list
      run: sudo apt-get update -y
    - name: dependencies
      run: sudo apt-get install -y libplist-dev libusb-1.0.0-dev libusbmuxd-dev libimobiledevice-dev
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make
