# This workflow will build usbmuxd

name: usbmuxd CI (no tests)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install -y libimobiledevice-dev libplist-dev libusb-1.0.0-dev
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make
